<?php


    $conn = oci_connect("system", "scott", "//localhost/XE");

    // Check connection
    if (!$conn) {
        $e = oci_error();
        trigger_error(htmlentities($e['message'], ENT_QUOTES), E_USER_ERROR);
    }

    $queryCreateTable = "
    CREATE TABLE AdoptiveParents (
        apid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255),
        age NUMBER,
        Financial_status VARCHAR2(255),
        AssignedHouse VARCHAR2(255),
        Gender VARCHAR2(255),
        Blood_group VARCHAR2(255),
        Health_Condition VARCHAR2(255),
        Marital_status VARCHAR2(255),
        Adoption_Status VARCHAR2(255),
        Email_address VARCHAR2(255)NOT NULL, 
        City VARCHAR2(255)
    );";

    $statementCreateTable = oci_parse($conn, $queryCreateTable);
    //oci_execute($statementCreateTable);
    oci_free_statement($statementCreateTable);

    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        $name = $_POST["name"];
        $age = $_POST["age"];
        $financialStatus = $_POST["financialStatus"];
        $assignedHouse = $_POST["assignedHouse"];
        $gender = $_POST["gender"];
        $bloodGroup = $_POST["bloodGroup"];
        $healthCondition = $_POST["healthCondition"];
        $maritalStatus = $_POST["maritalStatus"];
        $adoptionStatus = $_POST["adoptionStatus"];
        $emailAddress = $_POST["emailAddress"];
        $city = $_POST["city"];


        // Generating the next value for APID using a sequence
        $querySequence = "SELECT AdoptiveParents_apid.NEXTVAL AS NEW_APID FROM DUAL";
        $resultSequence = oci_parse($conn, $querySequence);
        oci_execute($resultSequence);
        $rowSequence = oci_fetch_assoc($resultSequence);
        $newApid = $rowSequence['NEW_APID'];
        oci_free_statement($resultSequence);

        
        // Inserting data into the AdoptiveParents table
        $queryInsert = "
        INSERT INTO AdoptiveParents (APID, name, age, Financial_status, AssignedHouse, Gender, Blood_group, Health_Condition, Marital_status, Adoption_Status, Email_address, City)
        VALUES (:newApid, :name, :age, :financialStatus, :assignedHouse, :gender, :bloodGroup, :healthCondition, :maritalStatus, :adoptionStatus, :emailAddress, :city)";

        $statementInsert = oci_parse($conn, $queryInsert);
        oci_bind_by_name($statementInsert, ":newApid", $newApid, -1, SQLT_INT);

        oci_bind_by_name($statementInsert, ":name", $name);
        oci_bind_by_name($statementInsert, ":age", $age);
        oci_bind_by_name($statementInsert, ":financialStatus", $financialStatus);
        oci_bind_by_name($statementInsert, ":assignedHouse", $assignedHouse);
        oci_bind_by_name($statementInsert, ":gender", $gender);
        oci_bind_by_name($statementInsert, ":bloodGroup", $bloodGroup);
        oci_bind_by_name($statementInsert, ":healthCondition", $healthCondition);
        oci_bind_by_name($statementInsert, ":maritalStatus", $maritalStatus);
        oci_bind_by_name($statementInsert, ":adoptionStatus", $adoptionStatus);
        oci_bind_by_name($statementInsert, ":emailAddress", $emailAddress);
        oci_bind_by_name($statementInsert, ":city", $city);

        $resultInsert = oci_execute($statementInsert);

        if ($resultInsert) {
            echo "Data inserted successfully! New APID: " . $newApid;

        } else {
            $error = oci_error($statementInsert);
            echo "Error: " . $error['message'];
        }
        if ($_SERVER["REQUEST_METHOD"] == "POST") 
        oci_free_statement($statementInsert);
        oci_close($conn);
    } else {
        echo "Form not submitted!";
    }
?>

<html>
<head>
<script>
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>
    <title>Registration</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <h1>DO You Need Child </h1>
    <form action=" " method="post">
        <fieldset>
            <legend>Adoptive Parents Registration</legend>
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" required>

            <label for="age">Age:</label>
            <input type="number" id="age" name="age" required>

            <label for="financialStatus">Financial Status:</label>
            <input type="text" id="financialStatus" name="financialStatus" required>

            <label for="assignedHouse">Assigned House:</label>
            <input type="text" id="assignedHouse" name="assignedHouse" required>

            <label for="gender">Gender:</label>
            <input type="text" id="gender" name="gender" required>

            <label for="bloodGroup">Blood Group:</label>
            <input type="text" id="bloodGroup" name="bloodGroup" required>

            <label for="healthCondition">Health Condition:</label>
            <input type="text" id="healthCondition" name="healthCondition" required>

            <label for="maritalStatus">Marital Status:</label>
            <input type="text" id="maritalStatus" name="maritalStatus" required>

            <label for="adoptionStatus">Adoption Status:</label>
            <input type="text" id="adoptionStatus" name="adoptionStatus" required>

            <label for="emailAddress">Email Address:</label>
            <input type="email" id="emailAddress" name="emailAddress" required>

            <label for="city">City:</label>
            <input type="text" id="city" name="city" required>

            <button type="submit">Register</button>
            
        </fieldset>
    </form>
    
       <!-- logout button -->
       <a href="welcome.php">Logout</a>

<!-- Main menu link -->
<a href="main.php">Main Menu</a>
    
</body>
</html>
